global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules.yaml"

scrape_configs:
  - job_name: 'flask-apps'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
    # Keep only containers with names like flask-app-1-v4.3.0 etc.
    - source_labels: [__meta_docker_container_name]
      regex: '/flask-app-.*'
      action: keep

    # Replace target address to always point to port 9100
    - source_labels: [__address__]
      target_label: __address__
      regex: '(.*):.*'
      replacement: '${1}:9100'
